name: ci-native

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Run native check
        run: nix run .#check --print-build-logs
