name: ci-native

on:
  workflow_call:
  workflow_dispatch:

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v14
      - name: Run native check
        run: nix run .#check
